spring:
  application:
    name: service-provider
  autoconfigure:
    exclude: org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration

feign.httpclient.enabled=false
feign.okhttp.enabled=true